use crate::error::Span;

#[derive(Debug, Clone, PartialEq)]
pub enum Tok {
    // literals / names
    Ident(String),
    Int(i64),
    Float(f64),
    Str(String),
    Char(char),
    Comment(String),

    // keywords
    Fn,
    Let,
    Var,
    Const,
    If,
    Else,
    For,
    While,
    Loop,
    Match,
    Struct,
    Enum,
    Import,
    Export,
    Return,
    Async,
    Await,
    Spawn,
    Unsafe,
    Trait,
    Impl,
    True,
    False,
    Some,
    None,
    Ok,
    Err,
    Test,
    Break,
    Continue,

    // punctuation / operators
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBrack,
    RBrack,
    Comma,
    Colon,
    Semi,
    Dot,
    DotDot,
    Question,
    At,
    Eq,
    EqEq,
    NotEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Bang,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    PipeGt,
    FatArrow,
    RetArrow,

    Newline,
    Eof,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: Tok,
    pub span: Span,
}

impl Token {
    pub fn is(&self, t: &Tok) -> bool {
        &self.kind == t
    }
}

pub fn describe(t: &Tok) -> String {
    match t {
        Tok::Ident(s) => format!("identifier `{}`", s),
        Tok::Int(n) => format!("`{}`", n),
        Tok::Float(n) => format!("`{}`", n),
        Tok::Str(_) => "string literal".into(),
        Tok::Char(_) => "character literal".into(),
        Tok::Comment(_) => "comment".into(),
        Tok::Fn => "`fn`".into(),
        Tok::Let => "`let`".into(),
        Tok::Var => "`var`".into(),
        Tok::Const => "`const`".into(),
        Tok::If => "`if`".into(),
        Tok::Else => "`else`".into(),
        Tok::For => "`for`".into(),
        Tok::While => "`while`".into(),
        Tok::Loop => "`loop`".into(),
        Tok::Match => "`match`".into(),
        Tok::Struct => "`struct`".into(),
        Tok::Enum => "`enum`".into(),
        Tok::Import => "`import`".into(),
        Tok::Export => "`export`".into(),
        Tok::Return => "`return`".into(),
        Tok::Async => "`async`".into(),
        Tok::Await => "`await`".into(),
        Tok::Spawn => "`spawn`".into(),
        Tok::Unsafe => "`unsafe`".into(),
        Tok::Trait => "`trait`".into(),
        Tok::Impl => "`impl`".into(),
        Tok::True => "`true`".into(),
        Tok::False => "`false`".into(),
        Tok::Some => "`Some`".into(),
        Tok::None => "`None`".into(),
        Tok::Ok => "`Ok`".into(),
        Tok::Err => "`Err`".into(),
        Tok::Test => "`test`".into(),
        Tok::Break => "`break`".into(),
        Tok::Continue => "`continue`".into(),
        Tok::LParen => "`(`".into(),
        Tok::RParen => "`)`".into(),
        Tok::LBrace => "`{`".into(),
        Tok::RBrace => "`}`".into(),
        Tok::LBrack => "`[`".into(),
        Tok::RBrack => "`]`".into(),
        Tok::Comma => "`,`".into(),
        Tok::Colon => "`:`".into(),
        Tok::Semi => "`;`".into(),
        Tok::Dot => "`.`".into(),
        Tok::DotDot => "`..`".into(),
        Tok::Question => "`?`".into(),
        Tok::At => "`@`".into(),
        Tok::Eq => "`=`".into(),
        Tok::EqEq => "`==`".into(),
        Tok::NotEq => "`!=`".into(),
        Tok::Lt => "`<`".into(),
        Tok::LtEq => "`<=`".into(),
        Tok::Gt => "`>`".into(),
        Tok::GtEq => "`>=`".into(),
        Tok::Plus => "`+`".into(),
        Tok::Minus => "`-`".into(),
        Tok::Star => "`*`".into(),
        Tok::Slash => "`/`".into(),
        Tok::Percent => "`%`".into(),
        Tok::Bang => "`!`".into(),
        Tok::Amp => "`&`".into(),
        Tok::AmpAmp => "`&&`".into(),
        Tok::Pipe => "`|`".into(),
        Tok::PipePipe => "`||`".into(),
        Tok::PipeGt => "`|>`".into(),
        Tok::FatArrow => "`=>`".into(),
        Tok::RetArrow => "`->`".into(),
        Tok::Newline => "newline".into(),
        Tok::Eof => "end of file".into(),
    }
}
